import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['es', 'en', 'de', 'pt', 'zh_Hans', 'fr', 'ru'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? esText = '',
    String? enText = '',
    String? deText = '',
    String? ptText = '',
    String? zh_HansText = '',
    String? frText = '',
    String? ruText = '',
  }) =>
      [
        esText,
        enText,
        deText,
        ptText,
        zh_HansText,
        frText,
        ruText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Entreno
  {
    'oavquopy': {
      'es': 'Pulsa 2 veces para reiniciar',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'eedp579f': {
      'es': '¿HAS TERMINADO?',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'sv7kx309': {
      'es': 'NO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'kj8fwy3t': {
      'es': 'SI',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '1bqwc1is': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Registrar
  {
    'm7d6smcx': {
      'es': 'BOX GYM',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '6qb3velc': {
      'es': 'Registrate',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'q13vvysp': {
      'es': 'Rellena los siguientes campos.',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'xwwstfqi': {
      'es': 'Correo',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'hscyj93y': {
      'es': 'Contraseña',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'xor3dhdw': {
      'es': 'Crear Cuenta',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'mvi4cztx': {
      'es': '¿Ya tienes una cuenta?  ',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '9wqjqs94': {
      'es': 'Entra aquí',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'vb2t9huo': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Login
  {
    '0ez5rp93': {
      'es': 'Login',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'p0vwlsgr': {
      'es': 'Rellene los campos con sus datos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'uibczuc9': {
      'es': 'Correo',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'gm2nmovp': {
      'es': 'Contraseña',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'o9l2ckfj': {
      'es': 'Iniciar Sesión',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qn1x9krv': {
      'es': '¿No Tienes Cuenta?',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'bgrps3im': {
      'es': 'Registrarse',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'kgpqs05w': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Main
  {
    'qhmstzl1': {
      'es': 'Entrena con naturalidad',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '4y8c1ep6': {
      'es': 'Mis Entrenamientos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '1ano4mej': {
      'es': 'Cardio  ',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '5858fjp2': {
      'es': 'Técnica',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '76v0ej7x': {
      'es': 'Fuerza',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'yyoys17k': {
      'es': 'Tienda de puntos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '3mti7gab': {
      'es': 'Eres un Administrador',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'c3kbjxpw': {
      'es': 'Listado de Entrenamientos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ua8otfst': {
      'es': 'Cardio  ',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'mx96gde1': {
      'es': 'Técnica',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'a32lvmc4': {
      'es': 'Fuerza',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '3cc99dum': {
      'es': 'Tienda de puntos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'gyj7p4l6': {
      'es': 'Perfil',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '7s2jx0ty': {
      'es': 'Ver Id',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'joo31o2f': {
      'es': 'Recompensas',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '69vcteod': {
      'es': 'Usuarios',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'jev9m6gr': {
      'es': 'Configuración',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'sxp4o3ty': {
      'es': 'Usuarios',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'i4c6yj5l': {
      'es': 'Configuración',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ir1x1waw': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Config
  {
    'e51id5qv': {
      'es': 'Editar Perfil',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'yqrd4xyf': {
      'es': 'Cambiar Contraseña',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '52o1fs1k': {
      'es': 'Cerrar Sesión',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '8xyjetcp': {
      'es': 'Eliminar Cuenta',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'a5u9o9nw': {
      'es': '__',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // crearEntreno
  {
    'id1c3nm6': {
      'es': 'Nombre...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'mpb5n8a6': {
      'es': 'Descripcion...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '3zrvo59f': {
      'es': 'Categoria',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'x82cy48y': {
      'es': 'Cardio',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'y1v0dk7c': {
      'es': 'Técnica',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'z15oyrnk': {
      'es': 'Fuerza',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'yjeg7sej': {
      'es': 'Entreno',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '0ih1js52': {
      'es': 'Correr',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'nnamhxu7': {
      'es': 'Sombra',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'pxswtgl3': {
      'es': 'Comba',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'l4sw99my': {
      'es': 'Selecciona el entrenamiento...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'lv9al205': {
      'es': 'Search for an item...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'pa16x449': {
      'es': 'Tiempo (mins)',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'rn0nvb9a': {
      'es': 'Crear Entreno',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'he895bi8': {
      'es': 'Nuevo Entreno',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'bah8x5ik': {
      'es': 'Configure su entreno.',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'eb6blr13': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // idVer
  {
    'gciznktb': {
      'es': '¡Aquí tienes tu tarjeta de identificación!',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '2koi62he': {
      'es': 'Reversa',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'bmglp57l': {
      'es': 'Escanea',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'wsw5013y': {
      'es': 'Cancel',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'j2rp636p': {
      'es': 'ID Personal',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'dbyl5k9f': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // cambioContrasena
  {
    'dg6xzhww': {
      'es': 'Back',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'iafap2x4': {
      'es': 'Contraseña olvidada',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '5mfn2jwe': {
      'es':
          'A continuación le enviaremos un correo para realizas el cambio de su contraseña',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'lb8mto6x': {
      'es': 'Direccion de correo...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'd5yw10v4': {
      'es': 'Introduzca su correo...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ysm82awe': {
      'es': 'Enviar Link',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'c5vv174s': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // empezarPerfil
  {
    'g0sv9jyf': {
      'es': 'Nombre de Usuario',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '9xsnudkx': {
      'es': 'Número de Teléfono',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'wq1jjk37': {
      'es': '18 o menos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '64ez8y6h': {
      'es': '18-24',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'r7cf5zqm': {
      'es': '24-40',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '12v156ej': {
      'es': '40-60',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '54k38109': {
      'es': '60 o más',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '3doi9u7s': {
      'es': 'Edad',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'tv2cycw0': {
      'es': 'Search for an item...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'lbq2cxbi': {
      'es': 'Guardar Datos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qzrpc47x': {
      'es': 'Crea tu Perfil',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // cambiosPerfil
  {
    'z3hxreep': {
      'es': 'Nombre de Usuario',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'l6wcq3tc': {
      'es': '18 o menos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'w46zy9r9': {
      'es': '18-24',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '5qphzuyp': {
      'es': '24-40',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'noeklaj2': {
      'es': '40-60',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qxkvospz': {
      'es': '60 o más',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'h1v5vpii': {
      'es': 'Edad',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'cz6cbyum': {
      'es': 'Search for an item...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '1x8qe96d': {
      'es': 'Guardar Cambios',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qm0z37an': {
      'es': 'Modifica tu Perfil',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Usuarios
  {
    'cs9awv3g': {
      'es': 'Usuarios',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'irwtaqbx': {
      'es': 'Busqueda',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '0ng5b9y4': {
      'es': 'Introduzca el nombre del usuario',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'wrchttg5': {
      'es': 'Limpiar',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'pqw9smby': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Perfil
  {
    'joxw13tk': {
      'es': 'Entrenamientos\nEmpezados',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'q6ts40my': {
      'es': 'Puntuación',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ozsxu2up': {
      'es': 'Entrenamientos\nCompletados',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'j8p184ko': {
      'es': 'Recompensas (Vista Previa)',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'lxq2nve7': {
      'es': 'Perfil',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'gdio1vre': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // modificarEntreno
  {
    '9c0be04t': {
      'es': 'Nombre...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '1xom4wqs': {
      'es': 'Descripcion...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    't8cxxbvn': {
      'es': 'Categoria',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'nhj2lf2l': {
      'es': 'Cardio',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'cztm6cve': {
      'es': 'Técnica',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ufzy8f5w': {
      'es': 'Fuerza',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ng5mcw0u': {
      'es': 'Entreno',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'nz0v1jxa': {
      'es': 'Correr',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ktk920fu': {
      'es': 'Sombra',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '1ynlf4qd': {
      'es': 'Comba',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '7lhm17q4': {
      'es': 'Selecciona el entrenamiento...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'dgsmpi37': {
      'es': 'Search for an item...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '10x6zekl': {
      'es': 'Tiempo (mins)',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'kepmvfah': {
      'es': 'Guardar Cambios',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'n0zzi9io': {
      'es': 'Modificar Entreno',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '32xp8dki': {
      'es': 'Realiza los cambios necesarios al entreno.',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'y81o6ytw': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Tienda
  {
    'gyi3swqd': {
      'es': '¡Obtén Recompensas!',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '8ofiz1sh': {
      'es': 'Tus Puntos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ierrbsyt': {
      'es': 'Tienda',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'i2jddke4': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Recompensas
  {
    'gxaw7prc': {
      'es': '¡Estos son tus items!',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '4vtle9mt': {
      'es': 'Devolver',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'lyjwkcxw': {
      'es': 'Recompensas',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'amtf13c2': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // crearEntrenoAdmin
  {
    'bdca1tl8': {
      'es': 'Nuevo Entreno',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ook6a3wz': {
      'es': 'Escribe el nombre y la categoria',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '7znno7o9': {
      'es': 'Categoria',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'v41hcg4k': {
      'es': 'Cardio',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'xnlq8nj5': {
      'es': 'Técnica',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'vwpl4jku': {
      'es': 'Fuerza',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '78r0c8ac': {
      'es': 'Nombre técnico',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '20819uip': {
      'es': 'Nombre...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '9cxkaasq': {
      'es': 'Crear Entreno',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'w8ayntst': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // crearItemAdmin
  {
    'dv10y13y': {
      'es': 'Nuevo Item',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'b96ag712': {
      'es': 'Escribe el nombre y puntos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qt53fiu7': {
      'es': 'Tipo item',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'j0w96iy2': {
      'es': 'Descuento',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'au8xycjo': {
      'es': 'Artículo',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '7rlqtsgz': {
      'es': 'Nombre item',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'dttc591e': {
      'es': 'Nombre...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'fc27nzty': {
      'es': 'Puntos necesarios',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'e3marvtr': {
      'es': 'Puntos...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '8xsov0tn': {
      'es': 'Crear Entreno',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'd2vrtfap': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // modificarItemAdmin
  {
    '6n7zg5bf': {
      'es': 'Modificar Item',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '99966z8t': {
      'es': 'Escribe el nombre y puntos',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '4iex8aso': {
      'es': 'Tipo item',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '6cb90632': {
      'es': 'Descuento',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'b3gicrxc': {
      'es': 'Artículo',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '49gfxqfd': {
      'es': 'Nombre item',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '9cq47blh': {
      'es': 'Nombre...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'zemjepv3': {
      'es': 'Puntos necesarios',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'o3nvpu0d': {
      'es': 'Puntos...',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'eyper7dr': {
      'es': 'Guardar Entreno',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'dqhm3zsy': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Tutorial
  {
    'hugo6zyz': {
      'es': '¡Aquí tienes un tutorial!',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'w9fwa5ub': {
      'es': 'Aprende como entrenar de la forma correcta',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'wzky0krn': {
      'es': 'Tutorial',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'yjniwrev': {
      'es': 'Home',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // confirmacionTerminar
  {
    'mvymuis0': {
      'es': '¿HAS TERMINADO?',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '7bksndvk': {
      'es': 'NO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'b4q3lhlh': {
      'es': 'SI',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // confirmacionEliminarEnt
  {
    'chkgqx0g': {
      'es': '¿Deseas eliminar este entrenamiento?',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '6fau7sih': {
      'es': 'NO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'rtrsq5dc': {
      'es': 'SI',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // accionesEntreno
  {
    'nc7my75g': {
      'es': 'ACCIONES:',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'y7dgo6up': {
      'es': 'Tiempo:',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'izr14xzr': {
      'es': 'Tutorial',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qwh6kwp9': {
      'es': 'Empezar',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'pzj5md6k': {
      'es': 'ACCIONES:',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // confirmacionEliminarUsu
  {
    '1eoh3q8d': {
      'es': '¿Deseas eliminar este usuario?',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '2ga68tqc': {
      'es': 'NO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'onr9yaus': {
      'es': 'SI',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // categoriaNoSeleccionada
  {
    '7l1aeypc': {
      'es': 'ALERTA',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'rvm1k6oj': {
      'es': 'DEBE SELECCIONAR UNA CATEGORIA',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'rx1b1rm2': {
      'es': 'ENTENDIDO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // noEntrenos
  {
    '2af4ggwh': {
      'es': 'NO HAY ENTRENAMIENTOS',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // confirmacionEliminarCuenta
  {
    'tlv362h3': {
      'es': '¿Desea eliminar su cuenta?',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'eefa72k1': {
      'es': 'NO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '4n5i7df0': {
      'es': 'SI',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // confirmacionEliminarItem
  {
    '6i738cn2': {
      'es': '¿Deseas eliminar este item?',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'fkmpe9do': {
      'es': 'NO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'rdlg12k6': {
      'es': 'SI',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // camposIncompletos
  {
    'jwnqf8yz': {
      'es': 'ALERTA',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '7csavqji': {
      'es': 'DEBE SELECCIONAR UNA CATEGORIA, ITEM Y PUNTOS',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'tq5nbp55': {
      'es': 'ENTENDIDO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // noItems
  {
    'jn4hrudx': {
      'es': 'NO HAY ITEMS',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // puntosInsuficientes
  {
    'jtlndh8q': {
      'es': 'ALERTA',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'cuhqd7x0': {
      'es': 'PUNTOS INSUFICENTES',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'm7lbut48': {
      'es': 'ENTENDIDO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // itemAdquirido
  {
    'kb3xu469': {
      'es': 'ENHORABUENA',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'v27akgww': {
      'es': '¡HAS ADQUIRIDO ESE ARTICULO!',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qe5644l6': {
      'es': 'ENTENDIDO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // confirmacionDevolverItem
  {
    'upmp5f4i': {
      'es': '¿Deseas devolver este item?',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '5tqwnlpr': {
      'es': 'NO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'o4lw6xez': {
      'es': 'SI',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // itemYaAdquirido
  {
    '6u71jkno': {
      'es': 'ALERTA',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'a01nyg2s': {
      'es': '¡YA TIENES ESTE ARTICULO!',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '5v293zei': {
      'es': 'ENTENDIDO',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    'k5glmoqj': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'r70pkvmb': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'f8rjrwso': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'awvfjfct': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'w6isf83n': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'jvv2vj9f': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ob7r3yf6': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '7uq3r10o': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'dtne1d0p': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qexfp29w': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'a21h8jjz': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'hledx5bj': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'artula96': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'n7nfm9nj': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'jisfb9ly': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'h551u3si': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '245yurtw': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'da4putxs': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'f2zowa29': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'txj17rgs': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '9zlzargj': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'uqb2pza9': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'uuw977y0': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'wvugo6bg': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'keelvfb7': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'xdqcy0em': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'uzdbyhpx': {
      'es': '',
      'de': '',
      'en': '',
      'fr': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
